// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AbiturientEntry is the predicate function for abituriententry builders.
type AbiturientEntry func(*sql.Selector)

// LastUpdated is the predicate function for lastupdated builders.
type LastUpdated func(*sql.Selector)
