// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AbiturientEntriesColumns holds the columns for the "abiturient_entries" table.
	AbiturientEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 1000},
		{Name: "number", Type: field.TypeInt64},
		{Name: "status", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "statement_given", Type: field.TypeBool, Default: false},
		{Name: "original_given", Type: field.TypeBool, Default: false},
		{Name: "speciality", Type: field.TypeString},
		{Name: "program", Type: field.TypeString},
		{Name: "form", Type: field.TypeEnum, Enums: []string{"och", "zaoch", "och-zaoch"}},
		{Name: "basis", Type: field.TypeString},
		{Name: "sum", Type: field.TypeInt64},
	}
	// AbiturientEntriesTable holds the schema information for the "abiturient_entries" table.
	AbiturientEntriesTable = &schema.Table{
		Name:        "abiturient_entries",
		Columns:     AbiturientEntriesColumns,
		PrimaryKey:  []*schema.Column{AbiturientEntriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// LastUpdatedsColumns holds the columns for the "last_updateds" table.
	LastUpdatedsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "last_updated", Type: field.TypeTime},
	}
	// LastUpdatedsTable holds the schema information for the "last_updateds" table.
	LastUpdatedsTable = &schema.Table{
		Name:        "last_updateds",
		Columns:     LastUpdatedsColumns,
		PrimaryKey:  []*schema.Column{LastUpdatedsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AbiturientEntriesTable,
		LastUpdatedsTable,
	}
)

func init() {
}
