// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"urfu-abiturient-api/ent/abituriententry"
	"urfu-abiturient-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AbiturientEntryQuery is the builder for querying AbiturientEntry entities.
type AbiturientEntryQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AbiturientEntry
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AbiturientEntryQuery builder.
func (aeq *AbiturientEntryQuery) Where(ps ...predicate.AbiturientEntry) *AbiturientEntryQuery {
	aeq.predicates = append(aeq.predicates, ps...)
	return aeq
}

// Limit adds a limit step to the query.
func (aeq *AbiturientEntryQuery) Limit(limit int) *AbiturientEntryQuery {
	aeq.limit = &limit
	return aeq
}

// Offset adds an offset step to the query.
func (aeq *AbiturientEntryQuery) Offset(offset int) *AbiturientEntryQuery {
	aeq.offset = &offset
	return aeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aeq *AbiturientEntryQuery) Unique(unique bool) *AbiturientEntryQuery {
	aeq.unique = &unique
	return aeq
}

// Order adds an order step to the query.
func (aeq *AbiturientEntryQuery) Order(o ...OrderFunc) *AbiturientEntryQuery {
	aeq.order = append(aeq.order, o...)
	return aeq
}

// First returns the first AbiturientEntry entity from the query.
// Returns a *NotFoundError when no AbiturientEntry was found.
func (aeq *AbiturientEntryQuery) First(ctx context.Context) (*AbiturientEntry, error) {
	nodes, err := aeq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{abituriententry.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aeq *AbiturientEntryQuery) FirstX(ctx context.Context) *AbiturientEntry {
	node, err := aeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AbiturientEntry ID from the query.
// Returns a *NotFoundError when no AbiturientEntry ID was found.
func (aeq *AbiturientEntryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aeq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{abituriententry.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aeq *AbiturientEntryQuery) FirstIDX(ctx context.Context) int {
	id, err := aeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AbiturientEntry entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AbiturientEntry entity is not found.
// Returns a *NotFoundError when no AbiturientEntry entities are found.
func (aeq *AbiturientEntryQuery) Only(ctx context.Context) (*AbiturientEntry, error) {
	nodes, err := aeq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{abituriententry.Label}
	default:
		return nil, &NotSingularError{abituriententry.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aeq *AbiturientEntryQuery) OnlyX(ctx context.Context) *AbiturientEntry {
	node, err := aeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AbiturientEntry ID in the query.
// Returns a *NotSingularError when exactly one AbiturientEntry ID is not found.
// Returns a *NotFoundError when no entities are found.
func (aeq *AbiturientEntryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aeq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = &NotSingularError{abituriententry.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aeq *AbiturientEntryQuery) OnlyIDX(ctx context.Context) int {
	id, err := aeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AbiturientEntries.
func (aeq *AbiturientEntryQuery) All(ctx context.Context) ([]*AbiturientEntry, error) {
	if err := aeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aeq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aeq *AbiturientEntryQuery) AllX(ctx context.Context) []*AbiturientEntry {
	nodes, err := aeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AbiturientEntry IDs.
func (aeq *AbiturientEntryQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := aeq.Select(abituriententry.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aeq *AbiturientEntryQuery) IDsX(ctx context.Context) []int {
	ids, err := aeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aeq *AbiturientEntryQuery) Count(ctx context.Context) (int, error) {
	if err := aeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aeq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aeq *AbiturientEntryQuery) CountX(ctx context.Context) int {
	count, err := aeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aeq *AbiturientEntryQuery) Exist(ctx context.Context) (bool, error) {
	if err := aeq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aeq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aeq *AbiturientEntryQuery) ExistX(ctx context.Context) bool {
	exist, err := aeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AbiturientEntryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aeq *AbiturientEntryQuery) Clone() *AbiturientEntryQuery {
	if aeq == nil {
		return nil
	}
	return &AbiturientEntryQuery{
		config:     aeq.config,
		limit:      aeq.limit,
		offset:     aeq.offset,
		order:      append([]OrderFunc{}, aeq.order...),
		predicates: append([]predicate.AbiturientEntry{}, aeq.predicates...),
		// clone intermediate query.
		sql:  aeq.sql.Clone(),
		path: aeq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AbiturientEntry.Query().
//		GroupBy(abituriententry.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (aeq *AbiturientEntryQuery) GroupBy(field string, fields ...string) *AbiturientEntryGroupBy {
	group := &AbiturientEntryGroupBy{config: aeq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aeq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aeq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AbiturientEntry.Query().
//		Select(abituriententry.FieldName).
//		Scan(ctx, &v)
//
func (aeq *AbiturientEntryQuery) Select(field string, fields ...string) *AbiturientEntrySelect {
	aeq.fields = append([]string{field}, fields...)
	return &AbiturientEntrySelect{AbiturientEntryQuery: aeq}
}

func (aeq *AbiturientEntryQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aeq.fields {
		if !abituriententry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aeq.path != nil {
		prev, err := aeq.path(ctx)
		if err != nil {
			return err
		}
		aeq.sql = prev
	}
	return nil
}

func (aeq *AbiturientEntryQuery) sqlAll(ctx context.Context) ([]*AbiturientEntry, error) {
	var (
		nodes = []*AbiturientEntry{}
		_spec = aeq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AbiturientEntry{config: aeq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, aeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aeq *AbiturientEntryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aeq.querySpec()
	return sqlgraph.CountNodes(ctx, aeq.driver, _spec)
}

func (aeq *AbiturientEntryQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := aeq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (aeq *AbiturientEntryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   abituriententry.Table,
			Columns: abituriententry.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: abituriententry.FieldID,
			},
		},
		From:   aeq.sql,
		Unique: true,
	}
	if unique := aeq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aeq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, abituriententry.FieldID)
		for i := range fields {
			if fields[i] != abituriententry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aeq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aeq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aeq *AbiturientEntryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aeq.driver.Dialect())
	t1 := builder.Table(abituriententry.Table)
	selector := builder.Select(t1.Columns(abituriententry.Columns...)...).From(t1)
	if aeq.sql != nil {
		selector = aeq.sql
		selector.Select(selector.Columns(abituriententry.Columns...)...)
	}
	for _, p := range aeq.predicates {
		p(selector)
	}
	for _, p := range aeq.order {
		p(selector)
	}
	if offset := aeq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aeq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AbiturientEntryGroupBy is the group-by builder for AbiturientEntry entities.
type AbiturientEntryGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aegb *AbiturientEntryGroupBy) Aggregate(fns ...AggregateFunc) *AbiturientEntryGroupBy {
	aegb.fns = append(aegb.fns, fns...)
	return aegb
}

// Scan applies the group-by query and scans the result into the given value.
func (aegb *AbiturientEntryGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aegb.path(ctx)
	if err != nil {
		return err
	}
	aegb.sql = query
	return aegb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := aegb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (aegb *AbiturientEntryGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(aegb.fields) > 1 {
		return nil, errors.New("ent: AbiturientEntryGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := aegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) StringsX(ctx context.Context) []string {
	v, err := aegb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aegb *AbiturientEntryGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aegb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = fmt.Errorf("ent: AbiturientEntryGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) StringX(ctx context.Context) string {
	v, err := aegb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (aegb *AbiturientEntryGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(aegb.fields) > 1 {
		return nil, errors.New("ent: AbiturientEntryGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := aegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) IntsX(ctx context.Context) []int {
	v, err := aegb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aegb *AbiturientEntryGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aegb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = fmt.Errorf("ent: AbiturientEntryGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) IntX(ctx context.Context) int {
	v, err := aegb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (aegb *AbiturientEntryGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(aegb.fields) > 1 {
		return nil, errors.New("ent: AbiturientEntryGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := aegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := aegb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aegb *AbiturientEntryGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aegb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = fmt.Errorf("ent: AbiturientEntryGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) Float64X(ctx context.Context) float64 {
	v, err := aegb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (aegb *AbiturientEntryGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(aegb.fields) > 1 {
		return nil, errors.New("ent: AbiturientEntryGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := aegb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := aegb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aegb *AbiturientEntryGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aegb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = fmt.Errorf("ent: AbiturientEntryGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aegb *AbiturientEntryGroupBy) BoolX(ctx context.Context) bool {
	v, err := aegb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aegb *AbiturientEntryGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aegb.fields {
		if !abituriententry.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aegb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aegb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aegb *AbiturientEntryGroupBy) sqlQuery() *sql.Selector {
	selector := aegb.sql
	columns := make([]string, 0, len(aegb.fields)+len(aegb.fns))
	columns = append(columns, aegb.fields...)
	for _, fn := range aegb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(aegb.fields...)
}

// AbiturientEntrySelect is the builder for selecting fields of AbiturientEntry entities.
type AbiturientEntrySelect struct {
	*AbiturientEntryQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aes *AbiturientEntrySelect) Scan(ctx context.Context, v interface{}) error {
	if err := aes.prepareQuery(ctx); err != nil {
		return err
	}
	aes.sql = aes.AbiturientEntryQuery.sqlQuery(ctx)
	return aes.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aes *AbiturientEntrySelect) ScanX(ctx context.Context, v interface{}) {
	if err := aes.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (aes *AbiturientEntrySelect) Strings(ctx context.Context) ([]string, error) {
	if len(aes.fields) > 1 {
		return nil, errors.New("ent: AbiturientEntrySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := aes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aes *AbiturientEntrySelect) StringsX(ctx context.Context) []string {
	v, err := aes.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (aes *AbiturientEntrySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aes.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = fmt.Errorf("ent: AbiturientEntrySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aes *AbiturientEntrySelect) StringX(ctx context.Context) string {
	v, err := aes.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (aes *AbiturientEntrySelect) Ints(ctx context.Context) ([]int, error) {
	if len(aes.fields) > 1 {
		return nil, errors.New("ent: AbiturientEntrySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := aes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aes *AbiturientEntrySelect) IntsX(ctx context.Context) []int {
	v, err := aes.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (aes *AbiturientEntrySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aes.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = fmt.Errorf("ent: AbiturientEntrySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aes *AbiturientEntrySelect) IntX(ctx context.Context) int {
	v, err := aes.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (aes *AbiturientEntrySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(aes.fields) > 1 {
		return nil, errors.New("ent: AbiturientEntrySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := aes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aes *AbiturientEntrySelect) Float64sX(ctx context.Context) []float64 {
	v, err := aes.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (aes *AbiturientEntrySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aes.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = fmt.Errorf("ent: AbiturientEntrySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aes *AbiturientEntrySelect) Float64X(ctx context.Context) float64 {
	v, err := aes.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (aes *AbiturientEntrySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(aes.fields) > 1 {
		return nil, errors.New("ent: AbiturientEntrySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := aes.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aes *AbiturientEntrySelect) BoolsX(ctx context.Context) []bool {
	v, err := aes.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (aes *AbiturientEntrySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aes.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{abituriententry.Label}
	default:
		err = fmt.Errorf("ent: AbiturientEntrySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aes *AbiturientEntrySelect) BoolX(ctx context.Context) bool {
	v, err := aes.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aes *AbiturientEntrySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aes.sqlQuery().Query()
	if err := aes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aes *AbiturientEntrySelect) sqlQuery() sql.Querier {
	selector := aes.sql
	selector.Select(selector.Columns(aes.fields...)...)
	return selector
}
