// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"urfu-abiturient-api/ent/migrate"

	"urfu-abiturient-api/ent/abituriententry"
	"urfu-abiturient-api/ent/lastupdated"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AbiturientEntry is the client for interacting with the AbiturientEntry builders.
	AbiturientEntry *AbiturientEntryClient
	// LastUpdated is the client for interacting with the LastUpdated builders.
	LastUpdated *LastUpdatedClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AbiturientEntry = NewAbiturientEntryClient(c.config)
	c.LastUpdated = NewLastUpdatedClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		AbiturientEntry: NewAbiturientEntryClient(cfg),
		LastUpdated:     NewLastUpdatedClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:          cfg,
		AbiturientEntry: NewAbiturientEntryClient(cfg),
		LastUpdated:     NewLastUpdatedClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AbiturientEntry.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AbiturientEntry.Use(hooks...)
	c.LastUpdated.Use(hooks...)
}

// AbiturientEntryClient is a client for the AbiturientEntry schema.
type AbiturientEntryClient struct {
	config
}

// NewAbiturientEntryClient returns a client for the AbiturientEntry from the given config.
func NewAbiturientEntryClient(c config) *AbiturientEntryClient {
	return &AbiturientEntryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `abituriententry.Hooks(f(g(h())))`.
func (c *AbiturientEntryClient) Use(hooks ...Hook) {
	c.hooks.AbiturientEntry = append(c.hooks.AbiturientEntry, hooks...)
}

// Create returns a create builder for AbiturientEntry.
func (c *AbiturientEntryClient) Create() *AbiturientEntryCreate {
	mutation := newAbiturientEntryMutation(c.config, OpCreate)
	return &AbiturientEntryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AbiturientEntry entities.
func (c *AbiturientEntryClient) CreateBulk(builders ...*AbiturientEntryCreate) *AbiturientEntryCreateBulk {
	return &AbiturientEntryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AbiturientEntry.
func (c *AbiturientEntryClient) Update() *AbiturientEntryUpdate {
	mutation := newAbiturientEntryMutation(c.config, OpUpdate)
	return &AbiturientEntryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AbiturientEntryClient) UpdateOne(ae *AbiturientEntry) *AbiturientEntryUpdateOne {
	mutation := newAbiturientEntryMutation(c.config, OpUpdateOne, withAbiturientEntry(ae))
	return &AbiturientEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AbiturientEntryClient) UpdateOneID(id int) *AbiturientEntryUpdateOne {
	mutation := newAbiturientEntryMutation(c.config, OpUpdateOne, withAbiturientEntryID(id))
	return &AbiturientEntryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AbiturientEntry.
func (c *AbiturientEntryClient) Delete() *AbiturientEntryDelete {
	mutation := newAbiturientEntryMutation(c.config, OpDelete)
	return &AbiturientEntryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *AbiturientEntryClient) DeleteOne(ae *AbiturientEntry) *AbiturientEntryDeleteOne {
	return c.DeleteOneID(ae.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *AbiturientEntryClient) DeleteOneID(id int) *AbiturientEntryDeleteOne {
	builder := c.Delete().Where(abituriententry.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AbiturientEntryDeleteOne{builder}
}

// Query returns a query builder for AbiturientEntry.
func (c *AbiturientEntryClient) Query() *AbiturientEntryQuery {
	return &AbiturientEntryQuery{
		config: c.config,
	}
}

// Get returns a AbiturientEntry entity by its id.
func (c *AbiturientEntryClient) Get(ctx context.Context, id int) (*AbiturientEntry, error) {
	return c.Query().Where(abituriententry.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AbiturientEntryClient) GetX(ctx context.Context, id int) *AbiturientEntry {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AbiturientEntryClient) Hooks() []Hook {
	return c.hooks.AbiturientEntry
}

// LastUpdatedClient is a client for the LastUpdated schema.
type LastUpdatedClient struct {
	config
}

// NewLastUpdatedClient returns a client for the LastUpdated from the given config.
func NewLastUpdatedClient(c config) *LastUpdatedClient {
	return &LastUpdatedClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `lastupdated.Hooks(f(g(h())))`.
func (c *LastUpdatedClient) Use(hooks ...Hook) {
	c.hooks.LastUpdated = append(c.hooks.LastUpdated, hooks...)
}

// Create returns a create builder for LastUpdated.
func (c *LastUpdatedClient) Create() *LastUpdatedCreate {
	mutation := newLastUpdatedMutation(c.config, OpCreate)
	return &LastUpdatedCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of LastUpdated entities.
func (c *LastUpdatedClient) CreateBulk(builders ...*LastUpdatedCreate) *LastUpdatedCreateBulk {
	return &LastUpdatedCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for LastUpdated.
func (c *LastUpdatedClient) Update() *LastUpdatedUpdate {
	mutation := newLastUpdatedMutation(c.config, OpUpdate)
	return &LastUpdatedUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *LastUpdatedClient) UpdateOne(lu *LastUpdated) *LastUpdatedUpdateOne {
	mutation := newLastUpdatedMutation(c.config, OpUpdateOne, withLastUpdated(lu))
	return &LastUpdatedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *LastUpdatedClient) UpdateOneID(id int) *LastUpdatedUpdateOne {
	mutation := newLastUpdatedMutation(c.config, OpUpdateOne, withLastUpdatedID(id))
	return &LastUpdatedUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for LastUpdated.
func (c *LastUpdatedClient) Delete() *LastUpdatedDelete {
	mutation := newLastUpdatedMutation(c.config, OpDelete)
	return &LastUpdatedDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *LastUpdatedClient) DeleteOne(lu *LastUpdated) *LastUpdatedDeleteOne {
	return c.DeleteOneID(lu.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *LastUpdatedClient) DeleteOneID(id int) *LastUpdatedDeleteOne {
	builder := c.Delete().Where(lastupdated.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &LastUpdatedDeleteOne{builder}
}

// Query returns a query builder for LastUpdated.
func (c *LastUpdatedClient) Query() *LastUpdatedQuery {
	return &LastUpdatedQuery{
		config: c.config,
	}
}

// Get returns a LastUpdated entity by its id.
func (c *LastUpdatedClient) Get(ctx context.Context, id int) (*LastUpdated, error) {
	return c.Query().Where(lastupdated.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *LastUpdatedClient) GetX(ctx context.Context, id int) *LastUpdated {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *LastUpdatedClient) Hooks() []Hook {
	return c.hooks.LastUpdated
}
