// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"urfu-abiturient-api/ent/lastupdated"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LastUpdatedCreate is the builder for creating a LastUpdated entity.
type LastUpdatedCreate struct {
	config
	mutation *LastUpdatedMutation
	hooks    []Hook
}

// SetLastUpdated sets the "last_updated" field.
func (luc *LastUpdatedCreate) SetLastUpdated(t time.Time) *LastUpdatedCreate {
	luc.mutation.SetLastUpdated(t)
	return luc
}

// Mutation returns the LastUpdatedMutation object of the builder.
func (luc *LastUpdatedCreate) Mutation() *LastUpdatedMutation {
	return luc.mutation
}

// Save creates the LastUpdated in the database.
func (luc *LastUpdatedCreate) Save(ctx context.Context) (*LastUpdated, error) {
	var (
		err  error
		node *LastUpdated
	)
	if len(luc.hooks) == 0 {
		if err = luc.check(); err != nil {
			return nil, err
		}
		node, err = luc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LastUpdatedMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = luc.check(); err != nil {
				return nil, err
			}
			luc.mutation = mutation
			node, err = luc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(luc.hooks) - 1; i >= 0; i-- {
			mut = luc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, luc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (luc *LastUpdatedCreate) SaveX(ctx context.Context) *LastUpdated {
	v, err := luc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (luc *LastUpdatedCreate) check() error {
	if _, ok := luc.mutation.LastUpdated(); !ok {
		return &ValidationError{Name: "last_updated", err: errors.New("ent: missing required field \"last_updated\"")}
	}
	return nil
}

func (luc *LastUpdatedCreate) sqlSave(ctx context.Context) (*LastUpdated, error) {
	_node, _spec := luc.createSpec()
	if err := sqlgraph.CreateNode(ctx, luc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (luc *LastUpdatedCreate) createSpec() (*LastUpdated, *sqlgraph.CreateSpec) {
	var (
		_node = &LastUpdated{config: luc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: lastupdated.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lastupdated.FieldID,
			},
		}
	)
	if value, ok := luc.mutation.LastUpdated(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: lastupdated.FieldLastUpdated,
		})
		_node.LastUpdated = value
	}
	return _node, _spec
}

// LastUpdatedCreateBulk is the builder for creating many LastUpdated entities in bulk.
type LastUpdatedCreateBulk struct {
	config
	builders []*LastUpdatedCreate
}

// Save creates the LastUpdated entities in the database.
func (lucb *LastUpdatedCreateBulk) Save(ctx context.Context) ([]*LastUpdated, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lucb.builders))
	nodes := make([]*LastUpdated, len(lucb.builders))
	mutators := make([]Mutator, len(lucb.builders))
	for i := range lucb.builders {
		func(i int, root context.Context) {
			builder := lucb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LastUpdatedMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lucb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lucb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lucb *LastUpdatedCreateBulk) SaveX(ctx context.Context) []*LastUpdated {
	v, err := lucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
