// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"urfu-abiturient-api/ent/lastupdated"
	"urfu-abiturient-api/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LastUpdatedQuery is the builder for querying LastUpdated entities.
type LastUpdatedQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LastUpdated
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LastUpdatedQuery builder.
func (luq *LastUpdatedQuery) Where(ps ...predicate.LastUpdated) *LastUpdatedQuery {
	luq.predicates = append(luq.predicates, ps...)
	return luq
}

// Limit adds a limit step to the query.
func (luq *LastUpdatedQuery) Limit(limit int) *LastUpdatedQuery {
	luq.limit = &limit
	return luq
}

// Offset adds an offset step to the query.
func (luq *LastUpdatedQuery) Offset(offset int) *LastUpdatedQuery {
	luq.offset = &offset
	return luq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (luq *LastUpdatedQuery) Unique(unique bool) *LastUpdatedQuery {
	luq.unique = &unique
	return luq
}

// Order adds an order step to the query.
func (luq *LastUpdatedQuery) Order(o ...OrderFunc) *LastUpdatedQuery {
	luq.order = append(luq.order, o...)
	return luq
}

// First returns the first LastUpdated entity from the query.
// Returns a *NotFoundError when no LastUpdated was found.
func (luq *LastUpdatedQuery) First(ctx context.Context) (*LastUpdated, error) {
	nodes, err := luq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{lastupdated.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (luq *LastUpdatedQuery) FirstX(ctx context.Context) *LastUpdated {
	node, err := luq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LastUpdated ID from the query.
// Returns a *NotFoundError when no LastUpdated ID was found.
func (luq *LastUpdatedQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = luq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{lastupdated.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (luq *LastUpdatedQuery) FirstIDX(ctx context.Context) int {
	id, err := luq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LastUpdated entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one LastUpdated entity is not found.
// Returns a *NotFoundError when no LastUpdated entities are found.
func (luq *LastUpdatedQuery) Only(ctx context.Context) (*LastUpdated, error) {
	nodes, err := luq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{lastupdated.Label}
	default:
		return nil, &NotSingularError{lastupdated.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (luq *LastUpdatedQuery) OnlyX(ctx context.Context) *LastUpdated {
	node, err := luq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LastUpdated ID in the query.
// Returns a *NotSingularError when exactly one LastUpdated ID is not found.
// Returns a *NotFoundError when no entities are found.
func (luq *LastUpdatedQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = luq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = &NotSingularError{lastupdated.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (luq *LastUpdatedQuery) OnlyIDX(ctx context.Context) int {
	id, err := luq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LastUpdateds.
func (luq *LastUpdatedQuery) All(ctx context.Context) ([]*LastUpdated, error) {
	if err := luq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return luq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (luq *LastUpdatedQuery) AllX(ctx context.Context) []*LastUpdated {
	nodes, err := luq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LastUpdated IDs.
func (luq *LastUpdatedQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := luq.Select(lastupdated.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (luq *LastUpdatedQuery) IDsX(ctx context.Context) []int {
	ids, err := luq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (luq *LastUpdatedQuery) Count(ctx context.Context) (int, error) {
	if err := luq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return luq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (luq *LastUpdatedQuery) CountX(ctx context.Context) int {
	count, err := luq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (luq *LastUpdatedQuery) Exist(ctx context.Context) (bool, error) {
	if err := luq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return luq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (luq *LastUpdatedQuery) ExistX(ctx context.Context) bool {
	exist, err := luq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LastUpdatedQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (luq *LastUpdatedQuery) Clone() *LastUpdatedQuery {
	if luq == nil {
		return nil
	}
	return &LastUpdatedQuery{
		config:     luq.config,
		limit:      luq.limit,
		offset:     luq.offset,
		order:      append([]OrderFunc{}, luq.order...),
		predicates: append([]predicate.LastUpdated{}, luq.predicates...),
		// clone intermediate query.
		sql:  luq.sql.Clone(),
		path: luq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LastUpdated time.Time `json:"last_updated,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LastUpdated.Query().
//		GroupBy(lastupdated.FieldLastUpdated).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (luq *LastUpdatedQuery) GroupBy(field string, fields ...string) *LastUpdatedGroupBy {
	group := &LastUpdatedGroupBy{config: luq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := luq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return luq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LastUpdated time.Time `json:"last_updated,omitempty"`
//	}
//
//	client.LastUpdated.Query().
//		Select(lastupdated.FieldLastUpdated).
//		Scan(ctx, &v)
//
func (luq *LastUpdatedQuery) Select(field string, fields ...string) *LastUpdatedSelect {
	luq.fields = append([]string{field}, fields...)
	return &LastUpdatedSelect{LastUpdatedQuery: luq}
}

func (luq *LastUpdatedQuery) prepareQuery(ctx context.Context) error {
	for _, f := range luq.fields {
		if !lastupdated.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if luq.path != nil {
		prev, err := luq.path(ctx)
		if err != nil {
			return err
		}
		luq.sql = prev
	}
	return nil
}

func (luq *LastUpdatedQuery) sqlAll(ctx context.Context) ([]*LastUpdated, error) {
	var (
		nodes = []*LastUpdated{}
		_spec = luq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LastUpdated{config: luq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, luq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (luq *LastUpdatedQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := luq.querySpec()
	return sqlgraph.CountNodes(ctx, luq.driver, _spec)
}

func (luq *LastUpdatedQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := luq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (luq *LastUpdatedQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   lastupdated.Table,
			Columns: lastupdated.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: lastupdated.FieldID,
			},
		},
		From:   luq.sql,
		Unique: true,
	}
	if unique := luq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := luq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, lastupdated.FieldID)
		for i := range fields {
			if fields[i] != lastupdated.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := luq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := luq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := luq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := luq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (luq *LastUpdatedQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(luq.driver.Dialect())
	t1 := builder.Table(lastupdated.Table)
	selector := builder.Select(t1.Columns(lastupdated.Columns...)...).From(t1)
	if luq.sql != nil {
		selector = luq.sql
		selector.Select(selector.Columns(lastupdated.Columns...)...)
	}
	for _, p := range luq.predicates {
		p(selector)
	}
	for _, p := range luq.order {
		p(selector)
	}
	if offset := luq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := luq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LastUpdatedGroupBy is the group-by builder for LastUpdated entities.
type LastUpdatedGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lugb *LastUpdatedGroupBy) Aggregate(fns ...AggregateFunc) *LastUpdatedGroupBy {
	lugb.fns = append(lugb.fns, fns...)
	return lugb
}

// Scan applies the group-by query and scans the result into the given value.
func (lugb *LastUpdatedGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lugb.path(ctx)
	if err != nil {
		return err
	}
	lugb.sql = query
	return lugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := lugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (lugb *LastUpdatedGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(lugb.fields) > 1 {
		return nil, errors.New("ent: LastUpdatedGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := lugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) StringsX(ctx context.Context) []string {
	v, err := lugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lugb *LastUpdatedGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = fmt.Errorf("ent: LastUpdatedGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) StringX(ctx context.Context) string {
	v, err := lugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (lugb *LastUpdatedGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(lugb.fields) > 1 {
		return nil, errors.New("ent: LastUpdatedGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := lugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) IntsX(ctx context.Context) []int {
	v, err := lugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lugb *LastUpdatedGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = fmt.Errorf("ent: LastUpdatedGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) IntX(ctx context.Context) int {
	v, err := lugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (lugb *LastUpdatedGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(lugb.fields) > 1 {
		return nil, errors.New("ent: LastUpdatedGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := lugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := lugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lugb *LastUpdatedGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = fmt.Errorf("ent: LastUpdatedGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) Float64X(ctx context.Context) float64 {
	v, err := lugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (lugb *LastUpdatedGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(lugb.fields) > 1 {
		return nil, errors.New("ent: LastUpdatedGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := lugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := lugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lugb *LastUpdatedGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = fmt.Errorf("ent: LastUpdatedGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lugb *LastUpdatedGroupBy) BoolX(ctx context.Context) bool {
	v, err := lugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lugb *LastUpdatedGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lugb.fields {
		if !lastupdated.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lugb *LastUpdatedGroupBy) sqlQuery() *sql.Selector {
	selector := lugb.sql
	columns := make([]string, 0, len(lugb.fields)+len(lugb.fns))
	columns = append(columns, lugb.fields...)
	for _, fn := range lugb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(lugb.fields...)
}

// LastUpdatedSelect is the builder for selecting fields of LastUpdated entities.
type LastUpdatedSelect struct {
	*LastUpdatedQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lus *LastUpdatedSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lus.prepareQuery(ctx); err != nil {
		return err
	}
	lus.sql = lus.LastUpdatedQuery.sqlQuery(ctx)
	return lus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lus *LastUpdatedSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lus *LastUpdatedSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lus.fields) > 1 {
		return nil, errors.New("ent: LastUpdatedSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lus *LastUpdatedSelect) StringsX(ctx context.Context) []string {
	v, err := lus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lus *LastUpdatedSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = fmt.Errorf("ent: LastUpdatedSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lus *LastUpdatedSelect) StringX(ctx context.Context) string {
	v, err := lus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lus *LastUpdatedSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lus.fields) > 1 {
		return nil, errors.New("ent: LastUpdatedSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lus *LastUpdatedSelect) IntsX(ctx context.Context) []int {
	v, err := lus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lus *LastUpdatedSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = fmt.Errorf("ent: LastUpdatedSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lus *LastUpdatedSelect) IntX(ctx context.Context) int {
	v, err := lus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lus *LastUpdatedSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lus.fields) > 1 {
		return nil, errors.New("ent: LastUpdatedSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lus *LastUpdatedSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lus *LastUpdatedSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = fmt.Errorf("ent: LastUpdatedSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lus *LastUpdatedSelect) Float64X(ctx context.Context) float64 {
	v, err := lus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lus *LastUpdatedSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lus.fields) > 1 {
		return nil, errors.New("ent: LastUpdatedSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lus *LastUpdatedSelect) BoolsX(ctx context.Context) []bool {
	v, err := lus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lus *LastUpdatedSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{lastupdated.Label}
	default:
		err = fmt.Errorf("ent: LastUpdatedSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lus *LastUpdatedSelect) BoolX(ctx context.Context) bool {
	v, err := lus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lus *LastUpdatedSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lus.sqlQuery().Query()
	if err := lus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lus *LastUpdatedSelect) sqlQuery() sql.Querier {
	selector := lus.sql
	selector.Select(selector.Columns(lus.fields...)...)
	return selector
}
