// Code generated by entc, DO NOT EDIT.

package ent

import (
	"urfu-abiturient-api/ent/abituriententry"
	"urfu-abiturient-api/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	abituriententryFields := schema.AbiturientEntry{}.Fields()
	_ = abituriententryFields
	// abituriententryDescName is the schema descriptor for name field.
	abituriententryDescName := abituriententryFields[0].Descriptor()
	// abituriententry.NameValidator is a validator for the "name" field. It is called by the builders before save.
	abituriententry.NameValidator = abituriententryDescName.Validators[0].(func(string) error)
	// abituriententryDescStatementGiven is the schema descriptor for statement_given field.
	abituriententryDescStatementGiven := abituriententryFields[4].Descriptor()
	// abituriententry.DefaultStatementGiven holds the default value on creation for the statement_given field.
	abituriententry.DefaultStatementGiven = abituriententryDescStatementGiven.Default.(bool)
	// abituriententryDescOriginalGiven is the schema descriptor for original_given field.
	abituriententryDescOriginalGiven := abituriententryFields[5].Descriptor()
	// abituriententry.DefaultOriginalGiven holds the default value on creation for the original_given field.
	abituriententry.DefaultOriginalGiven = abituriententryDescOriginalGiven.Default.(bool)
}
